# sonarcloud configuration for blackvuesync
sonar.projectKey=tekgnosis-net_blackvuesync
sonar.organization=tekgnosis-net

# project metadata
sonar.projectName=BlackVue Sync
sonar.projectVersion=2.3.0a0

# source code settings
sonar.sources=blackvuesync
sonar.tests=test,features
sonar.python.version=3.9

# coverage settings
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/*.js,**/*.html,**/*.css

# exclusions
sonar.exclusions=venv/**,build/**,dist/**,.venv/**,**/chart.umd.min.js,**/leaflet.js
sonar.test.exclusions=test/**,features/**

# encoding
sonar.sourceEncoding=UTF-8
